# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ancilla.Subconscious-Chat
PackageVersion: 0.1.11
InstallerType: nullsoft
NestedInstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
InstallModes:
- silent
- silentWithProgress
- interactive
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ancilla-Company/Subconscious/releases/download/v0.1.11/subconscious-setup-x64.exe
  InstallerSha256: 25E24BD91B53B3289E8FC56638BB9CF709C5CEB97F52F108ED71679F3CA3F2DB
ManifestType: installer
ManifestVersion: 1.12.0
