# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ancilla.Subconscious-Chat
PackageVersion: 0.1.11
InstallerType: nullsoft
NestedInstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
InstallModes:
- silent
- silentWithProgress
- interactive
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ancilla-Company/Subconscious/releases/download/v0.1.11/subconscious-setup-x64.exe
  InstallerSha256: 2EDBBBDBAA91C53C48F2A85ED42295FA8B5B30C5E4E162407BF36AA27CC7C693
ManifestType: installer
ManifestVersion: 1.12.0
