# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ancilla.Subconscious-Chat
PackageVersion: 0.1.11
InstallerType: nullsoft
NestedInstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
InstallModes:
- silent
- silentWithProgress
- interactive
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ancilla-Company/Subconscious/releases/download/v0.1.11/subconscious-setup-x64.exe
  InstallerSha256: 7BD34A7574ABD3DB4967E862E8455A4707FBA4ABC8A75BAE10C90342D58FBB4C
ManifestType: installer
ManifestVersion: 1.12.0
